### PR TITLE
Fix native extension load issue with Ruby 2.1.10

### PR DESCRIPTION
**Pull request by wpiekutowski**
Related issue: #55

### CODE REVIEW

**Comment by wpiekutowski** [comment]
1.9.3 is red. Unfortunately I can't figure out why as I can't reproduce this problem locally. It seems it started failing sometime earlier: https://travis-ci.org/copiousfreetime/hitimes/builds/95262500.
Are 1.9.3 and older still officially supported by this gem?

**Comment by copiousfreetime** [comment]
Officially I'm only supporting actively supported versions of ruby (which I should say in the readme). If it happens to work on an earlier version, that's a happy side effect. And I'll gladly accept pull requests that make things work on older versions of ruby if they don't.

I'll take a look at this pull request, and probably merge in the next day or so and see if I can replicate the 1.9.3 issue.

Thanks for finding my 2digit version bug :smile:

**Comment by wpiekutowski** [comment]
Thanks! Let me know if I can help. :)

Would there be any chance for a new patch release, if you decide to merge this?

**Comment by copiousfreetime** [comment]
Yes, I'll do a new release.

**Pull request merged**
